name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/hello-world-java

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set IMAGE_TAG to short SHA of commit
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Build project with Maven
      - name: Build with Maven
        run: mvn clean package --batch-mode

      # Build Docker image with dynamic tag
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Login to DockerHub
      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker image with dynamic tag
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      # Deploy using Helm with dynamic image tag
      - name: Helm Upgrade or Install
        run: |
          helm upgrade --install hello-world-java ./helm-hello-world-java \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=$IMAGE_TAG
