name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/hello-world-java

jobs:
  build-deploy-pr:
    runs-on: self-hosted

    steps:
      # Checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      # Set IMAGE_TAG to short commit SHA
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package --batch-mode

      # Build Docker image with tag = commit SHA
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      # DockerHub Login
      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker image
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Checkout GitOps repo
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: sujimatts/gitops-repo
          token: ${{ secrets.GH_PAT }}
          path: gitops-repo
          ref: main

      # Create branch, update tag, commit and push in one step
      - name: Create branch, update tag, commit and push
        run: |
          cd gitops-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b update-image-${{ env.IMAGE_TAG }}

          sed -i 's/^\s*tag:.*$/  tag: "'${{ env.IMAGE_TAG }}'"/' app1/values.yaml
          cat app1/values.yaml

          git add app1/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push --set-upstream origin update-image-${{ env.IMAGE_TAG }}

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          path: gitops-repo
          commit-message: Update image tag to ${{ env.IMAGE_TAG }}
          title: "[AutoPR] Update image tag to ${{ env.IMAGE_TAG }}"
          body: |
            This PR updates the Docker image tag in `app1/values.yaml` to `${{ env.IMAGE_TAG }}`.
          base: main
          branch: update-image-${{ env.IMAGE_TAG }}
